title: Import Documents
description: This add on allows you to submit a public Dropbox, Google Drive, WeTransfer, or MediaFire link and automatically upload it to DocumentCloud. Note that for now mostly only PDFs are functioning. In the future all 70 file extension types will be supported.  
type: object
properties:
 url:
  title: URL
  type: string
 project_id:
  title: Type the ID of the project you would like to upload the files to. 
  type: integer
access_level:
  title: Access level (public, private, or organization) of the documents you would like to upload. 
  type: string
  default: public
required:
 - url
 - project_id
