title: Document Transfer Tool
description: This add on allows you to submit a public Dropbox, Google Drive, WeTransfer, or MediaFire link and automatically upload it to DocumentCloud. 
type: object
properties:
 url:
  title: URL
  type: string
 project_name:
  title: Type the title of the project you would like to upload the files to. 
  type: string
required:
 - url
 - project_name
