title: Google Drive Upload AddOn
description: This add on allows you to submit a public Google Drive URL and automatically upload it to DocumentCloud. 
type: object
properties:
  url:
    title: URL
    type: string
